### ISSUE TITLE
Remove topic 'CodeIgniter4'

### ISSUE THREAD

**Issue by MGatner** [Redwoodcutter/SnProject#1]
Hi- your project is using CodeIgniter 3 but showing up when browsing the topic "CodeIgniter4". I'd recommend removing that topic unless you're planning to rewrite for version 4.

**Comment by Redwoodcutter** [comment]
i will do sorry for it, thanks for feedback

> Hi- your project is using CodeIgniter 3 but showing up when browsing the topic "CodeIgniter4". I'd recommend removing that topic unless you're planning to rewrite for version 4.
